export const ACTION_PROCESS_TICKS = 'PROCESS_TICKS';
export const ACTION_PURCHASE_UPGRADE = 'PURCHASE_UPGRADE';
export const ACTION_SET_INITIAL_MOVES = 'SET_INITIAL_MOVES';
export const ACTION_SET_PAUSED = 'SET_PAUSED';
export const ACTION_PRESTIGE = 'PRESTIGE';
export const ACTION_TIME_TRAVEL = 'TIME_TRAVEL';
export const ACTION_IMPORT_SAVE = 'IMPORT_SAVE';